### ISSUE TITLE
compare same test(s) against multiple versions of ember

### ISSUE THREAD

**Issue by stefanpenner** [eviltrout/ember-performance#17]
I typically care about comparing 2 different versions of ember, it would be great if we could select a group of ember.s to run a suite against.

**Comment by cowboyd** [comment]
Also, the ability to interleave sample taking between versions would strengthen the results. In other words, for a given test, take N samples with Ember A, then N samples with Ember B, then N samples with Ember A, and N samples with Ember B and so on, thereby diminishing the effects of any temporary computational context.

**Comment by stefanpenner** [comment]
@cowboyd +110000

**Comment by rwjblue** [comment]
@stefanpenner - Current master allows you to easily run the same test against multiple framework versions. Can this be closed?
