### ISSUE TITLE
npm install fails with node 0.12

### ISSUE THREAD

**Issue by tschneidereit** [eviltrout/ember-performance#37]
Because `broccoli-sass` depends on a version of `node-sass` that's not compatible with `0.12`.

**Comment by eviltrout** [comment]
This is waiting on this fix:

https://github.com/joliss/broccoli-sass/pull/43

Once brocolli-sass is fixed I can update package.json

**Comment by eviltrout** [comment]
Fixed here, thanks!

https://github.com/eviltrout/ember-performance/commit/7d01d2607bf648f026c947ebf04a932edc3f15fe
