### ISSUE TITLE
Using Ember > 1.12 uses non-prod versions of ember-metal.

### ISSUE THREAD

**Issue by rwjblue** [eviltrout/ember-performance#49]
This is because the ember-template-compiler.js contains `ember-metal` code but it is not in production mode (because we generally want deprecations and assertions to fire when precompiling templates).

**Comment by eviltrout** [comment]
Okay so the latest version no longer includes the template compiler. Instead, there's a first step where it compiles all the templates it needs and stores them in localStorage so they're available for each test.

It is slightly faster, but not considerably so: about 7% on my last run.
