### ISSUE TITLE
run a subset of tests against a subset of ember versions

### ISSUE THREAD

**Issue by stefanpenner** [eviltrout/ember-performance#59]
I would like to:
run: Ember.Object.Create + Ember.Component.create
against: 1.13.8, 2.0.2, release, beta, canary, custom

Today I must  queue up each different ember version independently, this is time consuming. Also in the end, I must manually aggregate and compare the results

@GavinJoyce unsure if you have time, but this would be really quite handy.

**Comment by GavinJoyce** [comment]
Sure, I've been planning to do this for a while. I'll begin working on this soon
