### ISSUE TITLE
Remove HTML results option

### ISSUE THREAD

**Issue by GavinJoyce** [eviltrout/ember-performance#62]
Do we need to support both HTML and text results? Perhaps we can just use the text version?

Once https://github.com/eviltrout/ember-performance/pull/61 lands I'm going to add some graphing capability which would augment the text results nicely

**Comment by stefanpenner** [comment]
text seems fine.

**Comment by stefanpenner** [comment]
@wycats you should be sure to share (unless you already have) your ascii histogram stuff

**Comment by GavinJoyce** [comment]
Thanks, I'll zap the HTML form in https://github.com/eviltrout/ember-performance/pull/61 as it's simpler than adding support for multiple results

**Comment by eviltrout** [comment]
I would prefer if we keep the HTML. However if there's a feature that's too hard to put in HTML, it would be okay if if we just had it in text. Long term HTML is a much nicer thing to share.

**Comment by GavinJoyce** [comment]
I'd like to come back to the results soon and add some graphs. I'll revisit the HTML option at that point
