### ISSUE TITLE
enable travis

### ISSUE THREAD

**Issue by stefanpenner** [eviltrout/ember-performance#93]
as of: https://github.com/eviltrout/ember-performance/commit/154ef1c7f5b96ea95e54f58a4e43fb12a07fa893 + https://github.com/eviltrout/ember-performance/commit/c8b14325b7b5fc6e6c5415d27b72b0291863d454 this repo has basic CI + a smoke test.

@eviltrout mind enabling travis from your end?

**Comment by eviltrout** [comment]
Enabled!

**Comment by stefanpenner** [comment]
thank you sir.
